CREATE TABLE "Ville" (
  id SERIAL PRIMARY KEY,
  id_Ville integer NULL,
  nom_Ville varchar(255)
);

INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (3,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (5,'Lille');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (7,'Amien');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (9,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (11,'Bordeaux');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (13,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (15,'Nantes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (17,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (19,'Orleans');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (21,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (23,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (25,'Bourges');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (27,'Amien');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (29,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (31,'Tours');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (33,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (35,'Saint etienne');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (37,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (39,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (41,'Nice');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (43,'Monaco');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (45,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (47,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (49,'Bordeaux');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (51,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (53,'Le Mans');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (55,'Cherbourg');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (57,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (59,'Angers');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (61,'Angers');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (63,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (65,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (67,'Le Mans');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (69,'Bordeaux');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (71,'Nantes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (73,'Saint Denis');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (75,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (77,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (79,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (81,'Nantes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (83,'Nantes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (85,'Angers');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (87,'Angers');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (89,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (91,'Amien');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (93,'Nice');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (95,'Saran');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (97,'Saran');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (99,'Toulouse');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (101,'Saint Denis');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (103,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (105,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (107,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (109,'Nantes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (111,'Bourges');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (113,'Bourges');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (115,'Cean');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (117,'Rouen');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (119,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (121,'Orleans');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (123,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (125,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (127,'Rouen');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (129,'Rouen');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (131,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (133,'Nantes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (135,'Laval');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (137,'Laval');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (139,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (141,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (143,'Tours');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (145,'Tours');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (147,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (149,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (151,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (153,'Rouen');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (155,'Laval');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (157,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (159,'Nice');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (161,'Nice');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (163,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (165,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (167,'Lille');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (169,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (171,'Nantes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (173,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (175,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (177,'Bordeaux');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (179,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (181,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (183,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (185,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (187,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (189,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (191,'Paris');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (193,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (195,'Marseille');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (197,'Marseille');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (199,'Rennes');
INSERT INTO "Ville" (id_Ville,nom_Ville) VALUES (201,'Nantes');
